name: CI
on: 
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check formatting
        run: make check-format

  build:
    name: Build client
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Enable long paths (Windows)
        if: runner.os == 'Windows'
        run: git config --system core.longpaths true
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build client
        run: make build

  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Enable long paths (Windows)
        if: runner.os == 'Windows'
        run: git config --system core.longpaths true
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run tests
        run: make test
